# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default:
            local:
                directory: "%kernel.project_dir%/public/uploads"
    filesystems:
        default:
            adapter: default
