security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        perform:
            entity:
                class: Perform\UserBundle\Entity\User
                property: email

    encoders:
        Perform\UserBundle\Entity\User:
            algorithm: bcrypt
    access_decision_manager:
        strategy: unanimous
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern: ^/
            form_login:
                login_path: perform_user_login
                check_path: perform_user_login
            logout:
                path: perform_user_logout
                target: /

    # Restrict all pages to logged-in users, but with an exception for
    # the login page so unauthenticated users can login
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgot-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
