product_crud:
    type: crud
    resource: product
    prefix: /products

actions:
    resource: '@PerformBaseBundle/Resources/config/routing/actions.yml'
    prefix: /_action

users:
    resource: "perform_user.user"
    type: crud
    prefix: /users

login:
    resource: '@PerformUserBundle/Resources/config/routing_login.yml'

forgot_password:
    resource: '@PerformUserBundle/Resources/config/routing/forgot_password.yml'
    prefix: /forgot-password
